function generation()
 { 
    var rase = document.getElementById("rase");
    var vR = rase.options[rase.selectedIndex].value; //pobieramy value rasy
    var origin = document.getElementById("origin");
    var vO = origin.options[origin.selectedIndex].value; //pobieramy value pochodzenia
    var male = document.getElementById("male");
	var vM = male.options[male.selectedIndex].value;	 //pobieramy value płci
	
	
	
	var ElfyOne = new Array(10);
	ElfyOne[0] = "Aes";
	ElfyOne[1] = "Ath";
	ElfyOne[2] = "Dor";
	ElfyOne[3] = "Far";
	ElfyOne[4] = "Gal";
	ElfyOne[5] = "Im";
	ElfyOne[6] = "Lin";
	ElfyOne[7] = "Mal";
	ElfyOne[8] = "Mor";
	ElfyOne[9] = "Ullia";
	
	var ElfyTwo = new Array(10);
	ElfyTwo[0] = "a";
	ElfyTwo[1] = "ath";
	ElfyTwo[2] = "dia";
	ElfyTwo[3] = "en";
	ElfyTwo[4] = "for";
	ElfyTwo[5] = "lor";
	ElfyTwo[6] = "mar";
	ElfyTwo[7] = "ol";
	ElfyTwo[8] = "sor";
	ElfyTwo[9] = "than";
	
	var ElfyLastForest = new Array(10);
	ElfyLastForest[0]= "arha";
	ElfyLastForest[1]= "anhu";
	ElfyLastForest[2]= "dda";
	ElfyLastForest[3]= "han";
	ElfyLastForest[4]= "loc";
	ElfyLastForest[5]= "noc";
	ElfyLastForest[6]= "oth";
	ElfyLastForest[7]= "ryn";
	ElfyLastForest[8]= "stra";
	ElfyLastForest[9]= "wyth";
	
	var ElfyLastW = new Array(10);
	ElfyLastW[0] = "andril";
	ElfyLastW[1] = "anel";
	ElfyLastW[2] = "elion";
	ElfyLastW[3] = "fin";
	ElfyLastW[4] = "il";
	ElfyLastW[5] = "irian";
	ElfyLastW[6] = "mor";
	ElfyLastW[7] = "nil";
	ElfyLastW[8] = "ric";
	ElfyLastW[9] = "wing";
	
var ElfyLastE = new Array(35);
ElfyLastE[0]="a";
ElfyLastE[1]="aine";
ElfyLastE[2]="ann";
ElfyLastE[3]="arma";
ElfyLastE[4]="arth";
ElfyLastE[5]="beann";
ElfyLastE[6]="brys";
ElfyLastE[7]="daen";
ElfyLastE[8]="deth";
ElfyLastE[9]="dys";
ElfyLastE[10]="drian";
ElfyLastE[11]="earna";
ElfyLastE[12]="earth";
ElfyLastE[13]="elle";
ElfyLastE[14]="felle";
ElfyLastE[15]="fynn";
ElfyLastE[16]="i";
ElfyLastE[17]="isa";
ElfyLastE[18]="leann";
ElfyLastE[19]="leath";
ElfyLastE[20]="lelle";
ElfyLastE[21]="nelle";
ElfyLastE[22]="niell";
ElfyLastE[23]="ni";
ElfyLastE[24]="ras";
ElfyLastE[25]="reann";
ElfyLastE[26]="rielle";
ElfyLastE[27]="sath";
ElfyLastE[28]="ser";
ElfyLastE[29]="sorth";
ElfyLastE[30]="teann";
ElfyLastE[31]="tir";
ElfyLastE[32]="tryan";
ElfyLastE[33]="yrs";
ElfyLastE[34]="ys";

var ElfSur = new Array(100);

ElfSur[0]="Białowłosy";
ElfSur[1]="Gwiazda Zaranna";
ElfSur[2]="Lśniący Grot";
ElfSur[3]="Opoka Siły";
ElfSur[4]="Smukły Grot";
ElfSur[5]="Wiatr Wśród Traw";
ElfSur[6]="Błękit Pióra";
ElfSur[7]="Gwiezdne Oko";
ElfSur[8]="Lśniący Księżyc";
ElfSur[9]="Orzeł Mroku";
ElfSur[10]="Spokój Fal";
ElfSur[11]="Wiatroskrzydly";
ElfSur[12]="Błękit Skrzydła";
ElfSur[13]="Gwiezdny Ogień";
ElfSur[14]="Mądre Serce";
ElfSur[15]="Ostre Ostrze";
ElfSur[16]="Spokój Kamienia";
ElfSur[17]="Wieża Mądrości";
ElfSur[18]="Błysk Klingi";
ElfSur[19]="Gwiezdny Pyl";
ElfSur[20]="Mądrość Klanu";
ElfSur[21]="Ostry Grot";
ElfSur[22]="Spokój Lasu";
ElfSur[23]="Wodny Wir";
ElfSur[24]="Błysk Pioruna";
ElfSur[25]="Jasna Gwiazda";
ElfSur[26]="Mężne Serce";
ElfSur[27]="Pajęcza Nić";
ElfSur[28]="Srebrnowłosy";
ElfSur[29]="Wschodzące Słońce";
ElfSur[30]="Błysk Stali";
ElfSur[31]="Jasnooki";
ElfSur[32]="Młody Liść";
ElfSur[33]="Patrzący W Dal";
ElfSur[34]="Srebrny Liść";
ElfSur[35]="Wszechwidzący";
ElfSur[36]="Bystrooki";
ElfSur[37]="Jastrzębie Oko";
ElfSur[38]="Moc Dębu";
ElfSur[39]="Podmuch Wichury";
ElfSur[40]="Srebrny Świt";
ElfSur[41]="Wyniosły Dąb";
ElfSur[42]="Ciemnowłosy";
ElfSur[43]="Jaśniejący";
ElfSur[44]="Moc Korzeni";
ElfSur[45]="Poranna Rosa";
ElfSur[46]="Strzała Mocy";
ElfSur[47]="Wysoki Brzeg";
ElfSur[48]="Cienista Dolina";
ElfSur[49]="Jeleni Skok";
ElfSur[50]="Moc Różdżki";
ElfSur[51]="Półksiężyc";
ElfSur[52]="Szybki Grot";
ElfSur[53]="Zachodzące Słońce";
ElfSur[54]="Czarne Drzewo ";
ElfSur[55]="Kieł Wilka";
ElfSur[56]="Morska Fala";
ElfSur[57]="Promyk Słońca ";
ElfSur[58]="Szybkie Ostrze";
ElfSur[59]="Zieleń Pióra";
ElfSur[60]="Czarny Kurhan";
ElfSur[61]="Korona Słońca";
ElfSur[62]="Morska Piana";
ElfSur[63]="Przyjaciel Zwierząt";
ElfSur[64]="Śnieżny Puch";
ElfSur[65]="Zieleń Skrzydła";
ElfSur[66]="Czysty Zdrój";
ElfSur[67]="Krzyk Puchacza";
ElfSur[68]="Mroczne Ostrze";
ElfSur[69]="Radosne Serce";
ElfSur[70]="Śpiew Dzikości";
ElfSur[71]="Zielona Dolina";
ElfSur[72]="Dech Lasu";
ElfSur[73]="Księżycowy Blask";
ElfSur[74]="Nocny Łowca";
ElfSur[75]="Różany Kwiat";
ElfSur[76]="Spiew Wiatru";
ElfSur[77]="Złocisty Oblok";
ElfSur[78]="Dębowy Konar";
ElfSur[79]="Księżycowy Mrok";
ElfSur[80]="Oko Wilka";
ElfSur[81]="Ryk Burzy";
ElfSur[82]="Ukryty W Cieniu";
ElfSur[83]="Złota Struga";
ElfSur[84]="Dotyk Nocy";
ElfSur[85]="Kwiat Młodości";
ElfSur[86]="Oko Wizji";
ElfSur[87]="Silnoręki";
ElfSur[88]="Uśmiech Wiatru";
ElfSur[89]="Złotowłosy";
ElfSur[90]="Dzikie Serce";
ElfSur[91]="Lot Sokoła";
ElfSur[92]="Oko Zieleni";
ElfSur[93]="Smoczy Brat";
ElfSur[94]="Wartki Strumyk";
ElfSur[95]="Gwiazda Wieczorna";
ElfSur[96]="Lśniąca Góra";
ElfSur[97]="Opadający Liść";
ElfSur[98]="Smukle Ostrze ";
ElfSur[99]="Wędrowiec";

var HumanNameM = new Array(152);
HumanNameM[0]= "Adalbert";
HumanNameM[1]= "Adalryk";
HumanNameM[2]= "Ademar";
HumanNameM[3]= "Adolf";
HumanNameM[4]= "Albert";
HumanNameM[5]= "Albrecht";
HumanNameM[6]= "Alfons";
HumanNameM[7]= "Alfred";
HumanNameM[8]= "Alodiusz";
HumanNameM[9]= "Alojzy";
HumanNameM[10]= "Alwin";
HumanNameM[11]= "Ansgar";
HumanNameM[12]= "Ansgary";
HumanNameM[13]= "Anzelm";
HumanNameM[14]= "Arbogast";
HumanNameM[15]= "Arbort";
HumanNameM[16]= "Armin";
HumanNameM[17]= "Arnold";
HumanNameM[18]= "Arnolf";
HumanNameM[19]= "Arwid";
HumanNameM[20]= "Aubert";
HumanNameM[21]= "Audomar";
HumanNameM[22]= "Baldomer";
HumanNameM[23]= "Baldwin";
HumanNameM[24]= "Beda";
HumanNameM[25]= "Bernard";
HumanNameM[26]= "Bernardyn";
HumanNameM[27]= "Bertold";
HumanNameM[28]= "Bertram";
HumanNameM[29]= "Bruno";
HumanNameM[30]= "Brunon";
HumanNameM[31]= "Burchard";
HumanNameM[32]= "Dagobert";
HumanNameM[33]= "Dypold";
HumanNameM[34]= "Dytwin";
HumanNameM[35]= "Edgar";
HumanNameM[36]= "Edmund";
HumanNameM[37]= "Edward";
HumanNameM[38]= "Edwin";
HumanNameM[39]= "Egbert";
HumanNameM[40]= "Egon";
HumanNameM[41]= "Egwin";
HumanNameM[42]= "Ekhard";
HumanNameM[43]= "Emeryk";
HumanNameM[44]= "Erbort";
HumanNameM[45]= "Ermenfryd";
HumanNameM[46]= "Ernest";
HumanNameM[47]= "Erwin";
HumanNameM[48]= "Eryk";
HumanNameM[49]= "Ewald";
HumanNameM[50]= "Ferdynand";
HumanNameM[51]= "Franciszek";
HumanNameM[52]= "Franciszek Salezy";
HumanNameM[53]= "Fryderyk";
HumanNameM[54]= "Gerald";
HumanNameM[55]= "Gerard";
HumanNameM[56]= "Germeriusz";
HumanNameM[57]= "Gerwazy";
HumanNameM[58]= "Gerwin";
HumanNameM[59]= "Ginter";
HumanNameM[60]= "Gizbert";
HumanNameM[61]= "Godfryd";
HumanNameM[62]= "Gotard";
HumanNameM[63]= "Gumbert";
HumanNameM[64]= "Gunter";
HumanNameM[65]= "Gundolf";
HumanNameM[66]= "Gustaw";
HumanNameM[67]= "Gwalbert";
HumanNameM[68]= "Gwido";
HumanNameM[69]= "Harald";
HumanNameM[70]= "Hekard";
HumanNameM[71]= "Helmut";
HumanNameM[72]= "Henryk";
HumanNameM[73]= "Herbert";
HumanNameM[74]= "Herbort";
HumanNameM[75]= "Herman";
HumanNameM[76]= "Hermenegild";
HumanNameM[77]= "Hildebrand";
HumanNameM[78]= "Hubert";
HumanNameM[79]= "Hugo";
HumanNameM[80]= "Hunold";
HumanNameM[81]= "Igor";
HumanNameM[82]= "Ildefons";
HumanNameM[83]= "Ingolf";
HumanNameM[84]= "Ingwar";
HumanNameM[85]= "Irmfryd";
HumanNameM[86]= "Jakert";
HumanNameM[87]= "Jurand";
HumanNameM[88]= "Karl";
HumanNameM[89]= "Konrad";
HumanNameM[90]= "Lambert";
HumanNameM[91]= "Leonard";
HumanNameM[92]= "Leopold";
HumanNameM[93]= "Lewin";
HumanNameM[94]= "Lotar";
HumanNameM[95]= "Lubart";
HumanNameM[96]= "Ludwik";
HumanNameM[97]= "Ludwin";
HumanNameM[98]= "Lutfryd";
HumanNameM[99]= "Majnard";
HumanNameM[100]= "Manfred";
HumanNameM[101]= "Markwart";
HumanNameM[102]= "Marold";
HumanNameM[103]= "Marwald";
HumanNameM[104]= "Medard";
HumanNameM[105]= "Odo";
HumanNameM[106]= "Odon";
HumanNameM[107]= "Odoryk";
HumanNameM[108]= "Odylon";
HumanNameM[109]= "Olaf";
HumanNameM[110]= "Oleg";
HumanNameM[111]= "Onold";
HumanNameM[112]= "Oskar";
HumanNameM[113]= "Osmund";
HumanNameM[114]= "Oswald";
HumanNameM[115]= "Otmar";
HumanNameM[116]= "Otokar";
HumanNameM[117]= "Otto";
HumanNameM[118]= "Rajmund";
HumanNameM[119]= "Rajner";
HumanNameM[120]= "Rajnold";
HumanNameM[121]= "Robert";
HumanNameM[122]= "Roderyk";
HumanNameM[123]= "Roger";
HumanNameM[124]= "Roland";
HumanNameM[125]= "Romuald";
HumanNameM[126]= "Rudolf";
HumanNameM[127]= "Ruprecht";
HumanNameM[128]= "Ryszard";
HumanNameM[129]= "Remigiusz";
HumanNameM[130]= "Roch";
HumanNameM[131]= "Sigmar";
HumanNameM[132]= "Sigmund";
HumanNameM[133]= "Teobald";
HumanNameM[134]= "Teodoryk";
HumanNameM[135]= "Tybald";
HumanNameM[136]= "Ulryk";
HumanNameM[137]= "Unold";
HumanNameM[138]= "Walbert";
HumanNameM[139]= "Waldebert";
HumanNameM[140]= "Waldemar";
HumanNameM[141]= "Walter";
HumanNameM[142]= "Wigbert";
HumanNameM[143]= "Wilhelm";
HumanNameM[144]= "Winand";
HumanNameM[145]= "Wulstan";
HumanNameM[146]= "Wunibald";
HumanNameM[147]= "Wolfram";
HumanNameM[148]= "Zybert";
HumanNameM[149]= "Zygfryd";
HumanNameM[150]= "Zygmunt";
HumanNameM[151]= "Zyndram";

var HumanNameE = new Array(106);
HumanNameE[1]=" Adalruna";
HumanNameE[2]=" Adalwina";
HumanNameE[3]=" Adela";
HumanNameE[4]=" Adelajda";
HumanNameE[5]=" Adelina";
HumanNameE[6]=" Adelinda";
HumanNameE[7]=" Alberta";
HumanNameE[8]=" Albertyna";
HumanNameE[9]=" Alicja";
HumanNameE[10]=" Alina";
HumanNameE[11]=" Alodia";
HumanNameE[12]=" Amelia";
HumanNameE[13]=" Baldomera";
HumanNameE[14]=" Baldwina";
HumanNameE[15]=" Batylda";
HumanNameE[16]=" Benona";
HumanNameE[17]=" Berengaria";
HumanNameE[18]=" Bernadeta";
HumanNameE[19]=" Bernarda";
HumanNameE[20]=" Bernardyna";
HumanNameE[21]=" Berta";
HumanNameE[22]=" Bertrada";
HumanNameE[23]=" Blanka";
HumanNameE[24]=" Dagmara";
HumanNameE[25]=" Edburga";
HumanNameE[26]=" Edeltruda";
HumanNameE[27]=" Edyta";
HumanNameE[28]=" Emeryka";
HumanNameE[29]=" Emnilda";
HumanNameE[30]=" Ermegarda";
HumanNameE[31]=" Ermelinda";
HumanNameE[32]=" Ermenfryda";
HumanNameE[33]=" Ermentruda";
HumanNameE[34]=" Ernesta";
HumanNameE[35]=" Ernestyna";
HumanNameE[36]=" Erwina";
HumanNameE[37]=" Eryka";
HumanNameE[38]=" Ewalda";
HumanNameE[39]=" Filiberta";
HumanNameE[40]=" Franciszka";
HumanNameE[41]=" Fryda";
HumanNameE[42]=" Fryderyka";
HumanNameE[43]=" Genowefa";
HumanNameE[44]=" Geraldyna";
HumanNameE[45]=" Gerarda";
HumanNameE[46]=" Gertruda";
HumanNameE[47]=" Gerwina";
HumanNameE[48]=" Gizela";
HumanNameE[49]=" Gryzelda";
HumanNameE[50]=" Gustawa";
HumanNameE[51]=" Helga";
HumanNameE[52]=" Henryka";
HumanNameE[53]=" Hermenegilda";
HumanNameE[54]=" Hildebranda";
HumanNameE[55]=" Huberta";
HumanNameE[56]=" Ida";
HumanNameE[57]=" Ildefonsa";
HumanNameE[58]=" Inga";
HumanNameE[59]=" Ingarda";
HumanNameE[60]=" Ingeborga";
HumanNameE[61]=" Ingryda";
HumanNameE[62]=" Irmegarda";
HumanNameE[63]=" Irmentruda";
HumanNameE[64]=" Irmfryda";
HumanNameE[65]=" Irmina";
HumanNameE[66]=" Iwona";
HumanNameE[67]=" Kanuta";
HumanNameE[68]=" Karolina";
HumanNameE[69]=" Kinga";
HumanNameE[70]=" Klotylda";
HumanNameE[71]=" Konrada";
HumanNameE[72]=" Kunegunda";
HumanNameE[73]=" Lamberta";
HumanNameE[74]=" Leonarda";
HumanNameE[75]=" Leopolda";
HumanNameE[76]=" Leopoldyna";
HumanNameE[77]=" Lorelei";
HumanNameE[78]=" Ludgarda";
HumanNameE[79]=" Ludolfina";
HumanNameE[80]=" Ludwika";
HumanNameE[81]=" Luiza";
HumanNameE[82]=" Malwina";
HumanNameE[83]=" Manfreda";
HumanNameE[84]=" Matylda";
HumanNameE[85]=" Mederyka";
HumanNameE[86]=" Mildreda";
HumanNameE[87]=" Oda";
HumanNameE[88]=" Olga";
HumanNameE[89]=" Oswalda";
HumanNameE[90]=" Otylia";
HumanNameE[91]=" Radegunda";
HumanNameE[92]=" Rajmunda";
HumanNameE[93]=" Roberta";
HumanNameE[94]=" Rozalinda";
HumanNameE[95]=" Rudolfa";
HumanNameE[96]=" Rudolfina";
HumanNameE[97]=" Ryksa";
HumanNameE[98]=" Ryszarda";
HumanNameE[99]=" Sigmunda";
HumanNameE[100]=" Walburga";
HumanNameE[101]=" Waldetruda";
HumanNameE[102]=" Waltrauda";
HumanNameE[103]=" Wilhelmina";
HumanNameE[104]=" Winanda";
HumanNameE[105]=" Zygfryda";
HumanNameE[0]=" Zygmunta";
 
var HumanSurname = new Array(26
);
HumanSurname[0]="Allenstag";
HumanSurname[1]="Atzwig";
HumanSurname[2]="Baade";
HumanSurname[3]="Bachmann";
HumanSurname[4]="Bischof";
HumanSurname[5]="Braun";
HumanSurname[6]="Ebberchard";
HumanSurname[7]="Fisher";
HumanSurname[8]="Godtgraf";
HumanSurname[9]="Halfzimmer";
HumanSurname[10]="Hallervorden";
HumanSurname[11]="Jauch";
HumanSurname[12]="Jutzenbach";
HumanSurname[13]="Kalkstein";
HumanSurname[14]="Lutzen";
HumanSurname[15]="Müller";
HumanSurname[16]="Neumann";
HumanSurname[17]="Nietzsche";
HumanSurname[18]="Reifsneider";
HumanSurname[19]="Schmidt";
HumanSurname[20]="Schneider";
HumanSurname[21]="Schultz";
HumanSurname[22]="Stieler";
HumanSurname[23]="Vogel";
HumanSurname[24]="Wagner";
HumanSurname[25]="Zimmermann";

var Dwarf = new Array(53);
Dwarf[1]="Al";
Dwarf[2]="Athran";
Dwarf[3]="Bal";
Dwarf[4]="Bara";
Dwarf[5]="Bela";
Dwarf[6]="Bok";
Dwarf[7]="Bur";
Dwarf[8]="Dam";
Dwarf[9]="Dora";
Dwarf[10]="Drok";
Dwarf[11]="Dwal";
Dwarf[12]="El";
Dwarf[13]="Elda";
Dwarf[14]="Fa";
Dwarf[15]="Fim";
Dwarf[16]="Firen";
Dwarf[17]="Fur";
Dwarf[18]="Gim";
Dwarf[19]="Gollen";
Dwarf[20]="Got";
Dwarf[21]="Grim";
Dwarf[22]="Grun";
Dwarf[23]="Hak";
Dwarf[24]="Haka";
Dwarf[25]="Hur";
Dwarf[26]="Kad";
Dwarf[27]="Kar";
Dwarf[28]="Katz";
Dwarf[29]="Logaz";
Dwarf[30]="Mola";
Dwarf[31]="Mor";
Dwarf[32]="Nola";
Dwarf[33]="Nor";
Dwarf[34]="Oda";
Dwarf[35]="Oka";
Dwarf[36]="Olf";
Dwarf[37]="Oth";
Dwarf[38]="Roran";
Dwarf[39]="Skalf";
Dwarf[40]="Skar";
Dwarf[41]="Snor";
Dwarf[42]="Sven";
Dwarf[43]="Thor";
Dwarf[44]="Thorn";
Dwarf[45]="Thura";
Dwarf[46]="Un";
Dwarf[47]="Utha";
Dwarf[48]="Ulla";
Dwarf[49]="Var";
Dwarf[50]="Zak";
Dwarf[51]="Zar";
Dwarf[52]="Zara";
Dwarf[0]="Zama";

var DwarfM = new Array(29);
DwarfM[0]="bin";
DwarfM[1]="bor";
DwarfM[2]="dok";
DwarfM[3]="drin";
DwarfM[4]="fin";
DwarfM[5]="gan";
DwarfM[6]="gar";
DwarfM[7]="gil";
DwarfM[8]="grom";
DwarfM[9]="grond";
DwarfM[10]="grunt";
DwarfM[11]="grim";
DwarfM[12]="kri";
DwarfM[13]="krag";
DwarfM[14]="li";
DwarfM[15]="lok";
DwarfM[16]="min";
DwarfM[17]="mir";
DwarfM[18]="rag";
DwarfM[19]="rig";
DwarfM[20]="rik";
DwarfM[21]="rin";
DwarfM[22]="skin";
DwarfM[23]="tin";
DwarfM[24]="tok";
DwarfM[25]="trek";
DwarfM[26]="trok";
DwarfM[27]="zin";
DwarfM[28]="zor";

var DwarfE = new Array(22);
DwarfE[0]="bora";
DwarfE[1]="dila";
DwarfE[2]="dokina";
DwarfE[3]="fina";
DwarfE[4]="fya";
DwarfE[5]="gara";
DwarfE[6]="grotha";
DwarfE[7]="gona";
DwarfE[8]="grimella";
DwarfE[9]="kya";
DwarfE[10]="lina";
DwarfE[11]="likina";
DwarfE[12]="luna";
DwarfE[13]="mina";
DwarfE[14]="mira";
DwarfE[15]="nina";
DwarfE[16]="ragina";
DwarfE[17]="riga";
DwarfE[18]="runa";
DwarfE[19]="toka";
DwarfE[20]="trekella";
DwarfE[21]="zora";
//Nazwiska krasnoludzkie tworzy się poprzez dodanie do imienia ojca końcówki "-sson" lub "-sdotr"w przypadku kobiet.

var Halfling = new Array(53);
Halfling[0]="Bag";
Halfling[1]="Balf";
Halfling[2]="Bere";
Halfling[3]="Bill";
Halfling[4]="Bobb";
Halfling[5]="Bog";
Halfling[6]="Bust";
Halfling[7]="Cam";
Halfling[8]="Ced";
Halfling[9]="Chund";
Halfling[10]="Clof";
Halfling[11]="Crum";
Halfling[12]="Dog";
Halfling[13]="Dott";
Halfling[14]="Dron";
Halfling[15]="Durc";
Halfling[16]="Elm";
Halfling[17]="Ermin";
Halfling[18]="Fald";
Halfling[19]="Fogg";
Halfling[20]="Ful";
Halfling[21]="Gaff";
Halfling[22]="Gamm";
Halfling[23]="Giff";
Halfling[24]="Gild";
Halfling[25]="Grop";
Halfling[26]="Gudd";
Halfling[27]="Ham";
Halfling[28]="Hal";
Halfling[29]="Joc";
Halfling[30]="Lac";
Halfling[31]="Lid";
Halfling[32]="Lob";
Halfling[33]="Lott";
Halfling[34]="Lure";
Halfling[35]="Mer";
Halfling[36]="Mul";
Halfling[37]="Murc";
Halfling[38]="May";
Halfling[39]="Nag";
Halfling[40]="Nobb";
Halfling[41]="Od";
Halfling[42]="Og";
Halfling[43]="Old";
Halfling[44]="Pipp";
Halfling[45]="Porc";
Halfling[46]="Riff";
Halfling[47]="Sam";
Halfling[48]="Supp";
Halfling[49]="Taff";
Halfling[50]="Tom";
Halfling[51]="Watt";
Halfling[52]="Will";

var HalfM = new Array(14);
HalfM[0]="belly";
HalfM[1]="er";
HalfM[2]="fast";
HalfM[3]="in";
HalfM[4]="it";
HalfM[5]="mutch";
HalfM[6]="o";
HalfM[7]="odoc";
HalfM[8]="riadoc";
HalfM[9]="regar";
HalfM[10]="wick";
HalfM[11]="wise";
HalfM[12]="wit";
HalfM[13]="y";

var HalfE = new Array(20);
HalfE[1]="a";
HalfE[2]="adell";
HalfE[3]="alot";
HalfE[4]="apple";
HalfE[5]="bell";
HalfE[6]="berry";
HalfE[7]="eena";
HalfE[8]="ella";
HalfE[9]="era";
HalfE[10]="et";
HalfE[11]="ia";
HalfE[12]="flower";
HalfE[13]="lotta";
HalfE[14]="petal";
HalfE[15]="riella";
HalfE[16]="sweet";
HalfE[17]="trude";
HalfE[18]="rose";
HalfE[19]="willow";
HalfE[0]="y";

var SurHalf = new Array(99);
SurHalf[0]="Altannik";
SurHalf[1]="Badylarz";
SurHalf[2]="Beczułka";
SurHalf[3]="Bielinek";
SurHalf[4]="Brzeżek";
SurHalf[5]="Brzuchacz";
SurHalf[6]="Cichobieg";
SurHalf[7]="Cierniak";
SurHalf[8]="Długonos";
SurHalf[9]="Długouch";
SurHalf[10]="Drapak";
SurHalf[11]="Drewniak";
SurHalf[12]="Dudziarz";
SurHalf[13]="Dziwaczek";
SurHalf[14]="Figlarz";
SurHalf[15]="Futrzak";
SurHalf[16]="Glistnik";
SurHalf[17]="Głuptak";
SurHalf[18]="Groszek";
SurHalf[19]="Grzechotek";
SurHalf[20]="Grzywacz";
SurHalf[21]="Gwizdawek";
SurHalf[22]="Iglarz";
SurHalf[23]="Jabłecznik";
SurHalf[24]="Jagódka";
SurHalf[25]="Jaskółka";
SurHalf[26]="Kaczeniec";
SurHalf[27]="Kasztanek";
SurHalf[28]="Kędziorek";
SurHalf[29]="Kociak";
SurHalf[30]="Kociołek";
SurHalf[31]="Kogut";
SurHalf[32]="Kolcownik";
SurHalf[33]="Koniczynka";
SurHalf[34]="Koralik";
SurHalf[35]="Kosturek";
SurHalf[36]="Kotlarz";
SurHalf[37]="Kret";
SurHalf[38]="Kręciołek";
SurHalf[39]="Kruczek";
SurHalf[40]="Krupnik";
SurHalf[41]="Kulawik";
SurHalf[42]="Kwietniak";
SurHalf[43]="Łazik";
SurHalf[44]="Łąkołaz";
SurHalf[45]="Łodyżek";
SurHalf[46]="Marudniak";
SurHalf[47]="Mieszek";
SurHalf[48]="Młynek";
SurHalf[49]="Morwa";
SurHalf[50]="Mroczek";
SurHalf[51]="Niemysł";
SurHalf[52]="Okruszek";
SurHalf[53]="Opijus";
SurHalf[54]="Otoczak";
SurHalf[55]="Owsianniak";
SurHalf[56]="Pagórek";
SurHalf[57]="Paluch";
SurHalf[58]="Piaszczak";
SurHalf[59]="Piwniak";
SurHalf[60]="Piwosz";
SurHalf[61]="Podpłomyk";
SurHalf[62]="Popiołek";
SurHalf[63]="Przebiśnieg";
SurHalf[64]="Radośnik";
SurHalf[65]="Robaczek";
SurHalf[66]="Rogaś";
SurHalf[67]="Ryjek";
SurHalf[68]="Rzęsawik";
SurHalf[69]="Sknerus";
SurHalf[70]="Skoblik";
SurHalf[71]="Skórniak";
SurHalf[72]="Słomnik";
SurHalf[73]="Stoczek";
SurHalf[74]="Stopowiąz";
SurHalf[75]="Stopowłaz";
SurHalf[76]="Sucharek";
SurHalf[77]="Szarak";
SurHalf[78]="Szarotek";
SurHalf[79]="Śnieżynka";
SurHalf[80]="Trrzęsawiec";
SurHalf[81]="Warkoczyk";
SurHalf[82]="Wąszacz";
SurHalf[83]="Wąwoźnik";
SurHalf[84]="Wesołek";
SurHalf[85]="Węgielek";
SurHalf[86]="Wiatrownik";
SurHalf[87]="Wierzbek";
SurHalf[88]="Wietrzyk";
SurHalf[89]="Wilczomlecz";
SurHalf[90]="Wilkowyj";
SurHalf[91]="Wodniak";
SurHalf[92]="Wstążka";
SurHalf[93]="Zagórnik";
SurHalf[94]="Zawijas";
SurHalf[95]="Zielniak";
SurHalf[96]="Złocisz";
SurHalf[97]="Żarnik";
SurHalf[98]="Żniwiarz";

var OkoL = new Array(9);

OkoL[0]="Zielony";
OkoL[1]="Jasnoniebieski";
OkoL[2]="Niebieski";
OkoL[3]="Blady Szary";
OkoL[4]="Szary";
OkoL[5]="Brązowy";
OkoL[6]="Orzechowy";
OkoL[7]="Ciemnobrązowy";
OkoL[8]="Czarny";

var OkoEW = new Array(10);

OkoEW[0]="Czarny jak smoła";
OkoEW[1]="Ametystowy";
OkoEW[2]="Akwamaryna";
OkoEW[3]="Szafirowy";
OkoEW[4]="Kasztanowy";
OkoEW[5]="Szmaragdowy";
OkoEW[6]="Bursztynowy";
OkoEW[7]="Miedziany";
OkoEW[8]="Cytrynowożółty";
OkoEW[9]="Złoty";

var OkoEL = new Array(10);

OkoEL[0]="Koloru kości słoniowej";
OkoEL[1]="Antracyt";
OkoEL[2]="Zielony jak bluszcz";
OkoEL[3]="Zielony jak mech";
OkoEL[4]="Chestnut";
OkoEL[5]="Kasztanowy";
OkoEL[6]="Ciemnobrązowy";
OkoEL[7]="Jasnobrązowy";
OkoEL[8]="Brązowy";
OkoEL[9]="Fiołkowy";

var OkoK = new Array(10);

OkoK[0]="Czarny jak węgiel";
OkoK[1]="Szary jak ołów";
OkoK[2]="Stalowoszary";
OkoK[3]="Niebieski";
OkoK[4]="Brązowy jak ziemia";
OkoK[5]="Ciemnobrązowy";
OkoK[6]="Orzechowy";
OkoK[7]="Zielony";
OkoK[8]="Ciemny miedziany";
OkoK[9]="Złoty";

var OkoN = new Array(10);

OkoN[0]="Jasnoszary";
OkoN[1]="Szary";
OkoN[2]="Błękitny";
OkoN[3]="Niebieski";
OkoN[4]="Turkusowy";
OkoN[5]="Orzechowy";
OkoN[6]="Brązowy";
OkoN[7]="Miedziany";
OkoN[8]="Brązowy";
OkoN[9]="Ciemnobrązowy";

var WagaALL = new Array(7);

WagaALL[0]="Wychydzonn";
WagaALL[1]="Chud";
WagaALL[2]="Szczupł";
WagaALL[3]="Normaln";
WagaALL[4]="Pulchn";
WagaALL[5]="Grub";
WagaALL[6]="Bardzo Tłust";

var HairL = new Array(10);

HairL[0]="Biały";
HairL[1]="Złoty blond";
HairL[2]="Rudoblond";
HairL[3]="Złoty";
HairL[4]="Jasny brąz";
HairL[5]="Ciemny brąz";
HairL[6]="Czarny";
HairL[7]="Kasztanowy";
HairL[8]="Rudy";
HairL[9]="Siwy";

var HairEL = new Array(10);

HairEL[0]="Brzozowobiały";
HairEL[1]="Blond";
HairEL[2]="Różowe złoto";
HairEL[3]="Miodowoblond";
HairEL[4]="Brązowy";
HairEL[5]="Mahoniowy";
HairEL[6]="Ciemny brąz";
HairEL[7]="Sjena";
HairEL[8]="Hebanowy";
HairEL[9]="Niebiesko-czarny";

var HairEW = new Array(10);

HairEW[0]="Srebrnosiwy";
HairEW[1]="Popielaty";
HairEW[2]="Jasny blond";
HairEW[3]="Miodowoblond";
HairEW[4]="Żółty";
HairEW[5]="Miedziany blond";
HairEW[6]="Blond";
HairEW[7]="Migdałowy";
HairEW[8]="Czerwony";
HairEW[9]="Czarny";

var HairK = new Array(10);

HairK[0]="Blond";
HairK[1]="Siwy";
HairK[2]="Jasny blond";
HairK[3]="Brązowy";
HairK[4]="Miedziany";
HairK[5]="Brąz";
HairK[6]="Brąz";
HairK[7]="Ciemny brąz";
HairK[8]="Rudy brąz";
HairK[9]="Czarny";

var HairN = new Array(10);

HairN[0]="Biały";
HairN[1]="Lniany";
HairN[2]="Rudawy";
HairN[3]="Złoty";
HairN[4]="Kasztanowy";
HairN[5]="Rudy";
HairN[6]="Musztardowy";
HairN[7]="Migdałowy";
HairN[8]="Czekoladowy";
HairN[9]="Lukrecjowy";



function humanMALE() {
	var yqe = Math.floor(Math.random() * 152);
	document.getElementById("nazwa").innerHTML = HumanNameM[yqe];
	var p = Math.floor(Math.random() * 26);
	document.getElementById("nazwisko").innerHTML = HumanSurname[p];
	var q = Math.floor(Math.random() * 9);
	document.getElementById("oczy").innerHTML = OkoL[q];
	var qwer = 145 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 15 + Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"y";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairL[wlos];

	var ww = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;

}
function humanFemale() {
	var yqe = Math.floor(Math.random() * 106);
	document.getElementById("nazwa").innerHTML = HumanNameE[yqe];
	var p = Math.floor(Math.random() * 26);
	document.getElementById("nazwisko").innerHTML = HumanSurname[p];
	var q = Math.floor(Math.random() * 9);
	document.getElementById("oczy").innerHTML = OkoL[q];
	var qwer = 145 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 15 + Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"a";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairL[wlos];

	var ww = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
function DwarfMALE() {
	var first = Math.floor(Math.random() * 53);
	var second	=	Math.floor(Math.random() * 29);
	document.getElementById("nazwa").innerHTML = Dwarf[first]+DwarfM[second];
	var first = Math.floor(Math.random() * 53);
	var second	=	Math.floor(Math.random() * 29);
	document.getElementById("nazwisko").innerHTML = Dwarf[first]+DwarfM[second]+"sson";
	var q = Math.floor(Math.random() * 9);
	document.getElementById("oczy").innerHTML = OkoK[q];
	var qwer = 130 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 15 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"y";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairK[wlos];

	var ww = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 10 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 40 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;

}
function DwarfFemale() {
	var first = Math.floor(Math.random() * 53);
	var second	=	Math.floor(Math.random() * 22);
	document.getElementById("nazwa").innerHTML = Dwarf[first]+DwarfE[second];
	var first = Math.floor(Math.random() * 53);
	var second	=	Math.floor(Math.random() * 29);
	document.getElementById("nazwisko").innerHTML = Dwarf[first]+DwarfM[second]+"sdotr";
	var q = Math.floor(Math.random() * 10);
	document.getElementById("oczy").innerHTML = OkoK[q];
	var qwer = 130 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 15 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"a";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairK[wlos];

	var ww = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 10 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 40 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
function ElfsW() {
	var yqe = Math.floor(Math.random() * 10);
	var yqw = Math.floor(Math.random() * 10);
	var yqq = Math.floor(Math.random() * 10);
	document.getElementById("nazwa").innerHTML = ElfyOne[yqe]+ElfyTwo[yqw]+ElfyLastW[yqq];
	var p = Math.floor(Math.random() * 100);
	document.getElementById("nazwisko").innerHTML = ElfSur[p];
	var q = Math.floor(Math.random() * 10);
	document.getElementById("oczy").innerHTML = OkoEW[q];
	var qwer = 180 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"y";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairEW[wlos];

	var ww = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 40 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
function ElfsL() {
	var yqe = Math.floor(Math.random() * 10);
	var yqw = Math.floor(Math.random() * 10);
	var yqq = Math.floor(Math.random() * 10);
	document.getElementById("nazwa").innerHTML = ElfyOne[yqe]+ElfyTwo[yqw]+ElfyLastForest[yqq];
	var p = Math.floor(Math.random() * 100);
	document.getElementById("nazwisko").innerHTML = ElfSur[p];
	var q = Math.floor(Math.random() * 10);
	document.getElementById("oczy").innerHTML = OkoEL[q];
	var qwer = 180 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"y";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairEL[wlos];

	var ww = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 40 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
function ElfsE() {
	var yqe = Math.floor(Math.random() * 10);
	var yqw = Math.floor(Math.random() * 10);
	var yqq = Math.floor(Math.random() * 35);
	document.getElementById("nazwa").innerHTML = ElfyOne[yqe]+ElfyTwo[yqw]+ElfyLastE[yqq];
	var p = Math.floor(Math.random() * 100);
	document.getElementById("nazwisko").innerHTML = ElfSur[p];
	var q = Math.floor(Math.random() * 10);
	document.getElementById("oczy").innerHTML = OkoEW[q];
	var qwer = 180 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1+ Math.floor(Math.random() * 10) + 1 + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"a";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairEW[wlos];

	var ww = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 40 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
function HalfMALE() {
	var yqe = Math.floor(Math.random() * 53);
	var yqw = Math.floor(Math.random() * 14);
	document.getElementById("nazwa").innerHTML = Halfling[yqe]+HalfM[yqw];
	var p = Math.floor(Math.random() * 99);
	document.getElementById("nazwisko").innerHTML = SurHalf[p];
	var q = Math.floor(Math.random() * 10);
	document.getElementById("oczy").innerHTML = OkoN[q];
	var qwer = 95 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 20 + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"y";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairN[wlos];

	var ww = 10 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 10 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
function HalfFEM() {
	var yqe = Math.floor(Math.random() * 53);
	var yqw = Math.floor(Math.random() * 20);
	document.getElementById("nazwa").innerHTML = Halfling[yqe]+HalfE[yqw];
	var p = Math.floor(Math.random() * 99);
	document.getElementById("nazwisko").innerHTML = SurHalf[p];
	var q = Math.floor(Math.random() * 10);
	document.getElementById("oczy").innerHTML = OkoN[q];
	var qwer = 95 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1 + " cm";
	document.getElementById("wzrost").innerHTML = qwer;
	var wiek = 20 + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + Math.floor(Math.random() * 10) + " lat";
	document.getElementById("age").innerHTML = wiek;
	var kilo = Math.floor(Math.random() * 7);
	document.getElementById("kilo").innerHTML = WagaALL[kilo]+"a";
	var wlos = Math.floor(Math.random() * 10);
	document.getElementById("wlosy").innerHTML = HairN[wlos];

	var ww = 10 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var us = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var s = 10 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var wt = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var i = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zw = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var zr = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var int = 20 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var sw = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	var ogd = 30 + Math.floor(Math.random() * 10) + 1 + Math.floor(Math.random() * 10) + 1
	document.getElementById("WW").innerHTML = ww;
	document.getElementById("US").innerHTML = us;
	document.getElementById("S").innerHTML = s;
	document.getElementById("WT").innerHTML = wt;
	document.getElementById("I").innerHTML = i;
	document.getElementById("ZW").innerHTML = zw;
	document.getElementById("ZR").innerHTML = zr;
	document.getElementById("INT").innerHTML = int;
	document.getElementById("SW").innerHTML = sw;
	document.getElementById("OGD").innerHTML = ogd;
}
	function check_with()
	{
		var option;
		if(vR=="l" && vM=="z"){
			window.onload = humanFemale();	
								}				
		else if(vR=="l"){
			window.onload = humanMALE();
						}
		else if(vR=="e" && vM=="z"){
			window.onload = ElfsE();
						}
		else if(vR=="e" && vO=="ult"){
			window.onload = ElfsW();
						}
		else if(vR=="e"){
			window.onload = ElfsL();
						}
		else if(vR=="k" && vM=="m"){
			window.onload = DwarfMALE();
						}
		else if(vR=="k"){
			window.onload = DwarfFemale();
						}
		else if(vR=="n" && vM=="m"){
			window.onload = HalfMALE();
						}
		else{
			window.onload = HalfFEM();
						}	
		//document.getElementById("nazwa").innerHTML = option;
				
								
	};
	window.onload = check_with();


	//function degog(){
		//if( vR="l"){
	//		i = Math.floor(Math.random() * 106);
	//		x = Math.floor(Math.random() * 26);
	//		document.getElementById("nazwa").innerHTML= HumanNameE[i];
	//		document.getElementById("nazwisko").innerHTML= HumanSurname[x];
		//	} else break;
	//}
 }	